allprojects {
    group = 'com.annaschneider.minecraft1'
    version = '2.0.0-fabric'
}

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.2')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
}
